+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n '' ']'
+ trap POST_TEST_DEFAULT EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Sat Apr 29 02:50:49 2023 - INFO  - Start to run test.
++ sysctl kernel.randomize_va_space
++ awk -F = '{ print $2 }'
+ getValue=' 1'
+ test 1 -eq 2
+ CHECK_RESULT 1 0 0 'check randomize_va_space set value fail'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='check randomize_va_space set value fail'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'check randomize_va_space set value fail'
+ LOG_ERROR 'check randomize_va_space set value fail'
+ message='check randomize_va_space set value fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'check randomize_va_space set value fail'
Sat Apr 29 02:50:50 2023 - ERROR - check randomize_va_space set value fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_check_runtime_security_001.sh line 31'
+ message='oe_test_check_runtime_security_001.sh line 31'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_check_runtime_security_001.sh line 31'
Sat Apr 29 02:50:51 2023 - ERROR - oe_test_check_runtime_security_001.sh line 31
+ '[' 0 -eq 1 ']'
+ return 0
++ sysctl fs.suid_dumpable
++ awk -F = '{ print $2 }'
+ getValue=' 2'
+ test 2 -eq 0
+ CHECK_RESULT 1 0 0 'check fs.suid_dumpable set value fail'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='check fs.suid_dumpable set value fail'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'check fs.suid_dumpable set value fail'
+ LOG_ERROR 'check fs.suid_dumpable set value fail'
+ message='check fs.suid_dumpable set value fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'check fs.suid_dumpable set value fail'
Sat Apr 29 02:50:52 2023 - ERROR - check fs.suid_dumpable set value fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_check_runtime_security_001.sh line 36'
+ message='oe_test_check_runtime_security_001.sh line 36'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_check_runtime_security_001.sh line 36'
Sat Apr 29 02:50:53 2023 - ERROR - oe_test_check_runtime_security_001.sh line 36
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Sat Apr 29 02:50:54 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sat Apr 29 02:50:54 2023 - ERROR - failed to execute the case.
+ exit 2
+ POST_TEST_DEFAULT
+ LOG_INFO 'oe_test_check_runtime_security_001.sh post_test'
+ message='oe_test_check_runtime_security_001.sh post_test'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'oe_test_check_runtime_security_001.sh post_test'
Sat Apr 29 02:50:55 2023 - INFO  - oe_test_check_runtime_security_001.sh post_test
