+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Fri Apr 28 22:28:06 2023 - INFO  - Start to prepare the database config.
+ DNF_INSTALL gcc
+ pkgs=gcc
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs gcc --node 1 --tempfile ''
Fri Apr 28 22:28:17 2023 - INFO  - pkgs:(gcc) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ [[ ! -f ./open_wo_file ]]
+ make
In file included from /usr/include/errno.h:28,
                 from open_wo_file.c:7:
/usr/include/bits/errno.h:26:11: fatal error: linux/errno.h: No such file or directory
   26 | # include <linux/errno.h>
      |           ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:4: default] Error 1
++ umask
+ ori_umask=0022
+ umask 002
+ LOG_INFO 'End to prepare the database config.'
+ message='End to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the database config.'
Fri Apr 28 22:28:19 2023 - INFO  - End to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Apr 28 22:28:20 2023 - INFO  - Start to run test.
+ echo test_wo_file
+ ./open_wo_file
oe_test_FSIO_open_wo_create_file.sh: line 34: ./open_wo_file: No such file or directory
+ CHECK_RESULT 127 0 0 'Write file failed while open file by write only.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Write file failed while open file by write only.'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Write file failed while open file by write only.'
+ LOG_ERROR 'Write file failed while open file by write only.'
+ message='Write file failed while open file by write only.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Write file failed while open file by write only.'
Fri Apr 28 22:28:21 2023 - ERROR - Write file failed while open file by write only.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_open_wo_create_file.sh line 35'
+ message='oe_test_FSIO_open_wo_create_file.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_open_wo_create_file.sh line 35'
Fri Apr 28 22:28:22 2023 - ERROR - oe_test_FSIO_open_wo_create_file.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ grep test_wo_file test_wo_file
grep: test_wo_file: No such file or directory
+ CHECK_RESULT 2 0 0 'The value is not written to file.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='The value is not written to file.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'The value is not written to file.'
+ LOG_ERROR 'The value is not written to file.'
+ message='The value is not written to file.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The value is not written to file.'
Fri Apr 28 22:28:23 2023 - ERROR - The value is not written to file.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_open_wo_create_file.sh line 37'
+ message='oe_test_FSIO_open_wo_create_file.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_open_wo_create_file.sh line 37'
Fri Apr 28 22:28:24 2023 - ERROR - oe_test_FSIO_open_wo_create_file.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ ls -l test_wo_file
+ awk '{print $0}'
+ grep '\-rwxrwxr\-x'
ls: cannot access 'test_wo_file': No such file or directorygrep: 
warning: stray \ before -
+ CHECK_RESULT 1 0 0 'The access of file is error.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The access of file is error.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The access of file is error.'
+ LOG_ERROR 'The access of file is error.'
+ message='The access of file is error.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The access of file is error.'
Fri Apr 28 22:28:25 2023 - ERROR - The access of file is error.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_open_wo_create_file.sh line 39'
+ message='oe_test_FSIO_open_wo_create_file.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_open_wo_create_file.sh line 39'
Fri Apr 28 22:28:26 2023 - ERROR - oe_test_FSIO_open_wo_create_file.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Apr 28 22:28:27 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Apr 28 22:28:27 2023 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Apr 28 22:28:28 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Fri Apr 28 22:28:29 2023 - WARN  - no thing to do.
+ return 0
+ rm -f test_wo_file
+ make clean
+ umask 0022
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Apr 28 22:28:31 2023 - INFO  - End to restore the test environment.
