+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n '' ']'
+ trap POST_TEST_DEFAULT EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Sat Apr 29 02:46:13 2023 - INFO  - Start to run test.
++ cat /etc/passwd
++ awk -F: '($1!="root" && $3<500 && $7!="/sbin/nologin" && $7!="/bin/false" && $7!="/bin/sync") {print}'
+ getValue='bin:x:1:1:bin:/bin:/usr/sbin/nologin
daemon:x:2:2:daemon:/sbin:/usr/sbin/nologin
adm:x:3:4:adm:/var/adm:/usr/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/usr/sbin/nologin
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/usr/sbin/nologin
operator:x:11:0:operator:/root:/usr/sbin/nologin
games:x:12:100:games:/usr/games:/usr/sbin/nologin
ftp:x:14:50:FTP User:/var/ftp:/usr/sbin/nologin'
+ echo bin:x:1:1:bin:/bin:/usr/sbin/nologin daemon:x:2:2:daemon:/sbin:/usr/sbin/nologin adm:x:3:4:adm:/var/adm:/usr/sbin/nologin lp:x:4:7:lp:/var/spool/lpd:/usr/sbin/nologin shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown halt:x:7:0:halt:/sbin:/sbin/halt mail:x:8:12:mail:/var/spool/mail:/usr/sbin/nologin operator:x:11:0:operator:/root:/usr/sbin/nologin games:x:12:100:games:/usr/games:/usr/sbin/nologin ftp:x:14:50:FTP User:/var/ftp:/usr/sbin/nologin
+ grep '[^\n]'
bin:x:1:1:bin:/bin:/usr/sbin/nologin daemon:x:2:2:daemon:/sbin:/usr/sbin/nologin adm:x:3:4:adm:/var/adm:/usr/sbin/nologin lp:x:4:7:lp:/var/spool/lpd:/usr/sbin/nologin shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown halt:x:7:0:halt:/sbin:/sbin/halt mail:x:8:12:mail:/var/spool/mail:/usr/sbin/nologin operator:x:11:0:operator:/root:/usr/sbin/nologin games:x:12:100:games:/usr/games:/usr/sbin/nologin ftp:x:14:50:FTP User:/var/ftp:/usr/sbin/nologin
+ CHECK_RESULT 0 0 1 'Check system account fail'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='Check system account fail'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'Check system account fail'
+ LOG_ERROR 'Check system account fail'
+ message='Check system account fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check system account fail'
Sat Apr 29 02:46:14 2023 - ERROR - Check system account fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_check_user_account_001.sh line 32'
+ message='oe_test_check_user_account_001.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_check_user_account_001.sh line 32'
Sat Apr 29 02:46:15 2023 - ERROR - oe_test_check_user_account_001.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ grep pam_wheel.so /etc/pam.d/su
+ grep required
#auth		required	pam_wheel.so use_uid
+ CHECK_RESULT 0 0 0 'not set wheel permission in /etc/pam.d/su'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='not set wheel permission in /etc/pam.d/su'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep sha512 /etc/pam.d/common-password
grep: /etc/pam.d/common-password: No such file or directory
+ CHECK_RESULT 2 0 0 'not set sha512 in /etc/pam.d/common-password'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='not set sha512 in /etc/pam.d/common-password'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'not set sha512 in /etc/pam.d/common-password'
+ LOG_ERROR 'not set sha512 in /etc/pam.d/common-password'
+ message='not set sha512 in /etc/pam.d/common-password'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'not set sha512 in /etc/pam.d/common-password'
Sat Apr 29 02:46:16 2023 - ERROR - not set sha512 in /etc/pam.d/common-password
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_check_user_account_001.sh line 40'
+ message='oe_test_check_user_account_001.sh line 40'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_check_user_account_001.sh line 40'
Sat Apr 29 02:46:17 2023 - ERROR - oe_test_check_user_account_001.sh line 40
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Sat Apr 29 02:46:17 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sat Apr 29 02:46:18 2023 - ERROR - failed to execute the case.
+ exit 2
+ POST_TEST_DEFAULT
+ LOG_INFO 'oe_test_check_user_account_001.sh post_test'
+ message='oe_test_check_user_account_001.sh post_test'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'oe_test_check_user_account_001.sh post_test'
Sat Apr 29 02:46:19 2023 - INFO  - oe_test_check_user_account_001.sh post_test
