+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Fri Apr 28 21:38:42 2023 - INFO  - Start to prepare the database config.
+ DNF_INSTALL gcc
+ pkgs=gcc
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs gcc --node 1 --tempfile ''
Fri Apr 28 21:38:54 2023 - INFO  - pkgs:(gcc) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ [[ ! -f ./aio_suspend_file ]]
+ make
In file included from /usr/include/sys/socket.h:33,
                 from aio_suspend_file.c:2:
/usr/include/bits/socket.h:359:11: fatal error: asm/socket.h: No such file or directory
  359 | # include <asm/socket.h>
      |           ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:4: default] Error 1
+ echo 'aio suspend file'
++ ls -l test_aio_suspend_file
++ awk '{print $5}'
+ filebytes=17
+ LOG_INFO 'End to prepare the database config.'
+ message='End to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the database config.'
Fri Apr 28 21:38:56 2023 - INFO  - End to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Apr 28 21:38:56 2023 - INFO  - Start to run test.
+ echo test_aio_suspend_file
+ ./aio_suspend_file
oe_test_FSIO_aio_suspend.sh: line 34: ./aio_suspend_file: No such file or directory
+ CHECK_RESULT 127 0 0 'Aio suspend file failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Aio suspend file failed.'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Aio suspend file failed.'
+ LOG_ERROR 'Aio suspend file failed.'
+ message='Aio suspend file failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Aio suspend file failed.'
Fri Apr 28 21:38:57 2023 - ERROR - Aio suspend file failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_aio_suspend.sh line 35'
+ message='oe_test_FSIO_aio_suspend.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_aio_suspend.sh line 35'
Fri Apr 28 21:38:58 2023 - ERROR - oe_test_FSIO_aio_suspend.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ grep test_aio_suspend_file test_aio_suspend_file
+ CHECK_RESULT 1 0 0 'Write info to file failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Write info to file failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Write info to file failed.'
+ LOG_ERROR 'Write info to file failed.'
+ message='Write info to file failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Write info to file failed.'
Fri Apr 28 21:38:59 2023 - ERROR - Write info to file failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_aio_suspend.sh line 37'
+ message='oe_test_FSIO_aio_suspend.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_aio_suspend.sh line 37'
Fri Apr 28 21:39:00 2023 - ERROR - oe_test_FSIO_aio_suspend.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Apr 28 21:39:01 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Apr 28 21:39:01 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Apr 28 21:39:02 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Fri Apr 28 21:39:03 2023 - WARN  - no thing to do.
+ return 0
+ rm -f test_aio_suspend_file
+ make clean
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Apr 28 21:39:04 2023 - INFO  - End to restore the test environment.
