+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Fri Apr 28 22:26:32 2023 - INFO  - Start to prepare the database config.
+ DNF_INSTALL gcc
+ pkgs=gcc
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs gcc --node 1 --tempfile ''
Fri Apr 28 22:26:43 2023 - INFO  - pkgs:(gcc) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ [[ ! -f ./open_notty_trun_file ]]
+ make
In file included from /usr/include/errno.h:28,
                 from open_notty_trun_file.c:7:
/usr/include/bits/errno.h:26:11: fatal error: linux/errno.h: No such file or directory
   26 | # include <linux/errno.h>
      |           ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:4: default] Error 1
+ echo 'test read only file'
+ LOG_INFO 'End to prepare the database config.'
+ message='End to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the database config.'
Fri Apr 28 22:26:45 2023 - INFO  - End to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Apr 28 22:26:46 2023 - INFO  - Start to run test.
+ echo test_notty_trun_file
+ ./open_notty_trun_file
oe_test_FSIO_open_noctty_trun_file.sh: line 33: ./open_notty_trun_file: No such file or directory
+ CHECK_RESULT 127 0 0 'Read or write file failed while open file by O_NOCTTY|O_TRUNC.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Read or write file failed while open file by O_NOCTTY|O_TRUNC.'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Read or write file failed while open file by O_NOCTTY|O_TRUNC.'
+ LOG_ERROR 'Read or write file failed while open file by O_NOCTTY|O_TRUNC.'
+ message='Read or write file failed while open file by O_NOCTTY|O_TRUNC.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Read or write file failed while open file by O_NOCTTY|O_TRUNC.'
Fri Apr 28 22:26:46 2023 - ERROR - Read or write file failed while open file by O_NOCTTY|O_TRUNC.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_open_noctty_trun_file.sh line 34'
+ message='oe_test_FSIO_open_noctty_trun_file.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_open_noctty_trun_file.sh line 34'
Fri Apr 28 22:26:47 2023 - ERROR - oe_test_FSIO_open_noctty_trun_file.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'test read only file' test_notty_trun_file
test read only file
+ CHECK_RESULT 0 1 0 'The orginal message on file doesn'\''t be cleared.'
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log='The orginal message on file doesn'\''t be cleared.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n 'The orginal message on file doesn'\''t be cleared.'
+ LOG_ERROR 'The orginal message on file doesn'\''t be cleared.'
+ message='The orginal message on file doesn'\''t be cleared.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The orginal message on file doesn'\''t be cleared.'
Fri Apr 28 22:26:48 2023 - ERROR - The orginal message on file doesn't be cleared.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_open_noctty_trun_file.sh line 36'
+ message='oe_test_FSIO_open_noctty_trun_file.sh line 36'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_open_noctty_trun_file.sh line 36'
Fri Apr 28 22:26:49 2023 - ERROR - oe_test_FSIO_open_noctty_trun_file.sh line 36
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Apr 28 22:26:50 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Apr 28 22:26:51 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Apr 28 22:26:51 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Fri Apr 28 22:26:52 2023 - WARN  - no thing to do.
+ return 0
+ rm -f test_notty_trun_file
+ make clean
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Apr 28 22:26:53 2023 - INFO  - End to restore the test environment.
