+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n '' ']'
+ trap POST_TEST_DEFAULT EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Sat Apr 29 02:48:14 2023 - INFO  - Start to run test.
+ grep '^PASS_MAX_DAYS' /etc/login.defs
PASS_MAX_DAYS	99999
+ CHECK_RESULT 0 0 0 'not set password PASS_MAX_DAYS'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='not set password PASS_MAX_DAYS'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep '^PASS_MIN_DAYS' /etc/login.defs
PASS_MIN_DAYS	0
+ CHECK_RESULT 0 0 0 'not set password PASS_MIN_DAYS'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='not set password PASS_MIN_DAYS'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep '^PASS_WARN_AGE' /etc/login.defs
PASS_WARN_AGE	7
+ CHECK_RESULT 0 0 0 'not set password PASS_WARN_AGE'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='not set password PASS_WARN_AGE'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ egrep '^\s*account\s+\[\s*success=1\s+new_authtok_reqd=done\s+default=ignore\s*\]\s+pam_unix.so' /etc/pam.d/common-account
+ CHECK_RESULT 2 0 0 'check PMA fail'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='check PMA fail'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'check PMA fail'
+ LOG_ERROR 'check PMA fail'
+ message='check PMA fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'check PMA fail'
Sat Apr 29 02:48:15 2023 - ERROR - check PMA fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_check_user_account_006.sh line 37'
+ message='oe_test_check_user_account_006.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_check_user_account_006.sh line 37'
Sat Apr 29 02:48:16 2023 - ERROR - oe_test_check_user_account_006.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Sat Apr 29 02:48:16 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 1
+ test 1 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sat Apr 29 02:48:17 2023 - ERROR - failed to execute the case.
+ exit 1
+ POST_TEST_DEFAULT
+ LOG_INFO 'oe_test_check_user_account_006.sh post_test'
+ message='oe_test_check_user_account_006.sh post_test'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'oe_test_check_user_account_006.sh post_test'
Sat Apr 29 02:48:18 2023 - INFO  - oe_test_check_user_account_006.sh post_test
